[package]
name = "ts-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
apache-avro = { version = "0.16.0", features = ["snappy"] }
chrono = "0.4.38"
redpanda-transform-sdk = "1.0.2"
redpanda-transform-sdk-sr = "1.0.2"

[profile.release]
lto = true

