redpanda:
  kafka_api:
    - name: internal
      address: 0.0.0.0
      port: 9092
      authentication_method: sasl
    - name: external
      address: 0.0.0.0
      port: 19092
      authentication_method: sasl
